### ISSUE TITLE
Is there any support for testing expectations?

### ISSUE THREAD

**Issue by foxyblocks** [playup/zucchini#2]
I wondering how you would go about having expectation style test steps with zucchini?

You know the "Then is should see <blank>" part of cucumber. 

This seemed to be missing from your examples.

Would it be possible to use assertion statements similar to what's described here? http://cocoamanifest.net/articles/2011/07/ui-automation-part-2-assertions-and-imports.html

Or is it only possible to test by comparing screenshots?

It seems that its missing the point of cucumbers "write the tests first" approach.

**Comment by ghost** [comment]
We are only using screenshot assertions in our projects but it doesn't mean you have to do it the same way: https://groups.google.com/forum/?fromgroups#!topic/zucchini-discuss/FQ0WSIX6Yak
